apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-demo-deploy-2
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: auto-demo-2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auto-demo-2
    spec:
      containers:
      - name: auto-demo-container-2
        image: shekeriev/k8s-jenkins:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: auto-demo-svc-2
  labels:
    app: auto-demo-2
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30003
    protocol: TCP
  selector:
    app: auto-demo-2
